#!/usr/bin/env python3
"""cookbook_index.py -- symptom index over cookbook/ (T8, Phase 1.7). Stdlib only.

  cookbook_index.py [--write]   regenerate docs/cookbook-symptoms.md from cookbook/, config/levers.tsv,
                                cookbook/C0002.md (triage table) and config/inherited_tells.tsv
  cookbook_index.py --check     verify; rc 1 on any finding (each printed `FAIL: ...`)

--check: every cookbook/C*.md has exactly one INDEX.md line and every INDEX line a file; every entry appears in
the rendered doc; every levers.tsv `cookbook` id and C0002 Entries id resolves to an indexed entry; C0002 TODO
rows render `untested` and agree with inherited_tells.tsv; doc not stale. Control: two scratch roots under
.run/cookbook_index/ (a planted C9999.md without an INDEX line; a levers.tsv row citing a missing id) must be
refused by the same check code, else `control: FAIL`. Read-only on cookbook/. No game bytes (G12).
"""
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOC = "docs/cookbook-symptoms.md"
GROUPS = ["expand-cse", "loop", "combine", "regalloc", "sched-reorg"]
ID_RE = re.compile(r"^C\d{4}$")


def read(path):
    return path.read_text(encoding="utf-8")


def load(root):
    """Parse every input under root. Returns (data, findings)."""
    f = []
    entries = {}
    for p in sorted((root / "cookbook").glob("C*.md")):
        lines = read(p).splitlines()
        m = re.match(r"^# (C\d{4}) — (.+)$", lines[0] if lines else "")
        if not m or m.group(1) != p.stem:
            f.append("%s: header line 1 is not `# %s — <title>`" % (p.name, p.stem))
            continue
        tags = []
        if len(lines) > 1 and lines[1].startswith("tags: "):
            tags = [t.strip() for t in lines[1][6:].split("·")[0].split(",") if t.strip()]
        else:
            f.append("%s: line 2 has no `tags:`" % p.name)
        tell = None
        for ln in lines[2:8]:
            if ln.startswith("tell: "):
                tell = ln[6:].strip()
                break
        entries[p.stem] = {"title": m.group(2).strip(), "tags": tags, "tell": tell}

    index = {}
    for n, ln in enumerate(read(root / "cookbook" / "INDEX.md").splitlines(), 1):
        if not ln.strip() or ln.startswith("<!--"):
            continue
        cid = ln.split(" | ")[0].strip()
        if not ID_RE.match(cid):
            f.append("INDEX.md:%d: malformed line" % n)
            continue
        index[cid] = index.get(cid, 0) + 1

    levers = []
    for ln in read(root / "config" / "levers.tsv").splitlines():
        if not ln.strip() or ln.startswith("#"):
            continue
        c = ln.split("\t")
        if len(c) != 10:
            f.append("levers.tsv: row `%s` has %d fields, want 10" % (c[0], len(c)))
            continue
        levers.append({"lever": c[0], "group": c[1], "cookbook": c[9].strip()})

    triage = []
    in_table = False
    for ln in read(root / "cookbook" / "C0002.md").splitlines():
        if ln.startswith("| Tell"):
            in_table = True
            continue
        if not in_table:
            continue
        if not ln.startswith("|"):
            break
        if ln.startswith("|---"):
            continue
        c = [x.strip() for x in ln.strip().strip("|").split("|")]
        if len(c) != 4:
            f.append("C0002.md: table row `%s` has %d columns, want 4" % (c[0], len(c)))
            continue
        triage.append({"tell": c[0], "entries": c[3]})

    inherited = {}
    for ln in read(root / "config" / "inherited_tells.tsv").splitlines():
        if not ln.strip() or ln.startswith("#"):
            continue
        c = ln.split("\t")
        if len(c) == 3:
            inherited[c[0]] = c[2].strip()
    return {"entries": entries, "index": index, "levers": levers, "triage": triage,
            "inherited": inherited}, f


def group_of(cid, e, levers):
    for r in levers:
        if r["cookbook"] == cid and r["group"] in GROUPS:
            return r["group"]
    for t in e["tags"]:
        if t in GROUPS:
            return t
    return None


def render(d):
    """Returns (doc text, set of ids rendered, findings)."""
    f = []
    seen = set()
    out = ["<!-- GENERATED by tools/cookbook_index.py --write from cookbook/, config/levers.tsv, cookbook/C0002.md,",
           "     config/inherited_tells.tsv. Never hand-edit; regenerate. Checked by tools/cookbook_index.py --check. -->",
           "# Cookbook symptom index", "",
           "Find the diff tell, open the entry. Pass groups as in docs/codegen-map.md.", "",
           "## Tells by pass group", ""]
    by_group = dict((g, []) for g in GROUPS)
    for cid in sorted(d["entries"]):
        e = d["entries"][cid]
        if e["tell"] is None:
            continue
        g = group_of(cid, e, d["levers"])
        if g is None:
            f.append("%s: has `tell:` but no group (no levers.tsv row, no group tag)" % cid)
            continue
        by_group[g].append("- %s -> %s — %s" % (e["tell"], cid, e["title"]))
        seen.add(cid)
    for g in GROUPS:
        out += ["### " + g, ""] + (by_group[g] or ["- none"]) + [""]
    out += ["## Inherited tells (C0002)", ""]
    for r in d["triage"]:
        ids = "untested" if r["entries"] == "TODO" else r["entries"]
        out.append("- %s -> %s" % (r["tell"], ids))
    out += ["", "## By tag", ""]
    tags = {}
    for cid, e in d["entries"].items():
        if e["tell"] is not None:
            continue
        for t in e["tags"]:
            tags.setdefault(t, set()).add(cid)
        if e["tags"]:
            seen.add(cid)
    for t in sorted(tags):
        out.append("- `%s`: %s" % (t, ", ".join(sorted(tags[t]))))
    return "\n".join(out) + "\n", seen, f


def check(root):
    """Returns (findings, entries total, entries indexed, refs total, refs resolved)."""
    d, f = load(root)
    text, seen, rf = render(d)
    f += rf
    ents, index = d["entries"], d["index"]
    ok = 0
    for cid in sorted(ents):
        n = index.get(cid, 0)
        if n != 1:
            f.append("%s.md: %d INDEX.md lines, want 1" % (cid, n))
        if cid not in seen:
            f.append("%s: not in the rendered doc" % cid)
        if n == 1 and cid in seen:
            ok += 1
    for cid in sorted(index):
        if cid not in ents:
            f.append("INDEX.md: %s has no cookbook/%s.md" % (cid, cid))
    indexed = set(c for c in ents if index.get(c) == 1)
    refs = good = 0
    for r in d["levers"]:
        refs += 1
        if r["cookbook"] in indexed:
            good += 1
        else:
            f.append("levers.tsv: %s cites %s, not an indexed entry" % (r["lever"], r["cookbook"]))
    for r in d["triage"]:
        inh = d["inherited"].get(r["tell"])
        if r["entries"] == "TODO":
            refs += 1
            if inh == "untested":
                good += 1
            else:
                f.append("C0002 TODO row `%s`: inherited_tells.tsv levers=%s, want untested" % (r["tell"], inh))
            continue
        if inh is None or inh == "untested":
            f.append("C0002 row `%s` has entries but inherited_tells.tsv levers=%s" % (r["tell"], inh))
        for cid in [x.strip() for x in r["entries"].split(",")]:
            refs += 1
            if cid in indexed:
                good += 1
            else:
                f.append("C0002 row `%s` cites %s, not an indexed entry" % (r["tell"], cid))
    doc = root / DOC
    if not doc.exists() or read(doc) != text:
        f.append("%s is stale; run tools/cookbook_index.py --write" % DOC)
    return f, len(ents), ok, refs, good


def scratch(name):
    """Copy the inputs and the doc into .run/cookbook_index/<name>/."""
    s = ROOT / ".run" / "cookbook_index" / name
    if s.exists():
        shutil.rmtree(str(s))
    shutil.copytree(str(ROOT / "cookbook"), str(s / "cookbook"))
    (s / "config").mkdir(parents=True)
    (s / "docs").mkdir()
    for rel in ("config/levers.tsv", "config/inherited_tells.tsv", DOC):
        if (ROOT / rel).exists():
            shutil.copy2(str(ROOT / rel), str(s / rel))
    return s


def control():
    s = scratch("plant_index")
    (s / "cookbook" / "C9999.md").write_text(
        "# C9999 — planted control entry\ntags: control · date: - · phase/task: - · origin: -\n", encoding="utf-8")
    a = any(x.startswith("C9999.md: 0 INDEX.md lines") for x in check(s)[0])
    s = scratch("plant_ref")
    p = s / "config" / "levers.tsv"
    p.write_text(read(p) + "planted\tcombine\tt\tUNKNOWN\ta\t0x0\t0x4\tb.c\ta.c\tC9998\n", encoding="utf-8")
    b = any(x.startswith("levers.tsv: planted cites C9998") for x in check(s)[0])
    return a and b


def main(argv):
    if argv not in ([], ["--write"], ["--check"]):
        print("usage: cookbook_index.py [--write | --check]", file=sys.stderr)
        return 2
    if argv != ["--check"]:
        d, f = load(ROOT)
        text, _, rf = render(d)
        for x in f + rf:
            print("FAIL: " + x)
        (ROOT / DOC).write_text(text, encoding="utf-8")
        print("wrote %s" % DOC)
        return 1 if f + rf else 0
    f, n, ok, refs, good = check(ROOT)
    for x in f:
        print("FAIL: " + x)
    print("cookbook-index: %d of %d entries indexed" % (ok, n))
    print("refs: %d of %d resolve" % (good, refs))
    c = control()
    print("control: " + ("ok" if c else "FAIL"))
    return 1 if f or not c else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
