#!/usr/bin/env python3
"""tools/loadmap.py -- generate / check config/loadmap.tsv (T6).

Inputs: extracted/retail/manifest.jsonl (path, size, sha1) + config/loadmap.evidence.tsv
(path class route base status basis). Output: config/loadmap.tsv, one row per manifest .BIN
plus SLUS_012.79, sorted by path, TAB-separated, LF, no timestamps. Only sha1 hex and
addresses are written (G12).

  loadmap.py                  write the out file, print rows=<r> N=<n>
  loadmap.py --check          regenerate in memory, compare to the out file, assert the
                              row / class / end / control-row checks, run a negative control
  --ledger PATH / --out PATH  override the evidence ledger / the out file
"""
import argparse
import json
import re
import shutil
import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "extracted/retail/manifest.jsonl"
EXE_PATH = "SLUS_012.79"
EXE_FILE = ROOT / "extracted/retail/files" / EXE_PATH
CLASSES = ("exe", "code", "data", "debug", "stub")
COLS = ("path", "size", "sha1", "class", "route", "base", "end", "status")
BLOCK = 50  # a '#' comment line every <= 50 data rows


class CheckError(Exception):
    pass


def read_manifest():
    recs = {}
    for line in MANIFEST.read_text().splitlines():
        if line.strip():
            r = json.loads(line)
            if r["path"].endswith(".BIN") or r["path"] == EXE_PATH:
                recs[r["path"]] = r
    return recs


def read_ledger(path):
    rows = {}
    for n, line in enumerate(Path(path).read_text().splitlines(), 1):
        if not line or line.startswith("#"):
            continue
        f = line.split("\t")
        if len(f) != 6:
            raise CheckError(f"ledger {path}:{n}: expected 6 fields, got {len(f)}")
        if f[0] in rows:
            raise CheckError(f"ledger {path}:{n}: duplicate path {f[0]}")
        rows[f[0]] = dict(zip(("path", "class", "route", "base", "status", "basis"), f))
    return rows


def exe_header():
    hdr = EXE_FILE.read_bytes()[:0x20]
    return struct.unpack_from("<II", hdr, 0x18)  # t_addr, t_size


def build(ledger_path):
    """Return (rows, problems). rows: list of dicts sorted by path."""
    man = read_manifest()
    led = read_ledger(ledger_path)
    problems = []
    for p in sorted(set(led) - set(man)):
        problems.append(f"ledger row not in manifest set: {p}")
    for p in sorted(set(man) - set(led)):
        problems.append(f"manifest path missing from ledger: {p}")
    rows = []
    for p in sorted(set(man) & set(led)):
        m, l = man[p], led[p]
        base = l["base"]
        if base == "-":
            end = "-"
        else:
            b = int(base, 16)
            if l["class"] == "exe":
                t_addr, t_size = exe_header()
                if t_addr != b:
                    problems.append(f"{p}: header t_addr 0x{t_addr:08x} != ledger base 0x{b:08x}")
                end = f"0x{t_addr + t_size:08x}"
            else:
                end = f"0x{b + m['size']:08x}"
            base = f"0x{b:08x}"
        rows.append({"path": p, "size": str(m["size"]), "sha1": m["sha1"], "class": l["class"],
                     "route": l["route"], "base": base, "end": end, "status": l["status"],
                     "basis": l["basis"]})
    return rows, problems


def count_n(rows):
    return sum(r["class"] in ("exe", "code") for r in rows)


def render(rows):
    n = count_n(rows)
    out = [
        "# config/loadmap.tsv -- generated by tools/loadmap.py from extracted/retail/manifest.jsonl"
        " + config/loadmap.evidence.tsv; do not hand-edit.",
        f"# N = {n} (rows with class exe|code); rows = {len(rows)}; see docs/memory-map.md#load-map",
        "# " + "\t".join(COLS),
    ]
    for i, r in enumerate(rows):
        if i and i % BLOCK == 0:
            out.append(f"# rows {i + 1}..")
        out.append("\t".join(r[c] for c in COLS))
    return "\n".join(out) + "\n"


def doc_section(doc_path, anchor):
    lines = (ROOT / doc_path).read_text().splitlines()
    tag = f'<a id="{anchor}"></a>'
    try:
        i = next(k for k, ln in enumerate(lines) if ln.strip() == tag)
    except StopIteration:
        raise CheckError(f"anchor {doc_path}#{anchor} not found")
    j = i + 1
    while j < len(lines) and not lines[j].startswith("#"):
        j += 1
    if j == len(lines):
        raise CheckError(f"{doc_path}#{anchor}: no heading after anchor")
    level = len(lines[j]) - len(lines[j].lstrip("#"))
    k = j + 1
    while k < len(lines):
        h = lines[k]
        if h.startswith("#") and len(h) - len(h.lstrip("#")) <= level:
            break
        k += 1
    return lines[j:k]


RE_BASE = re.compile(r"\bbase (?:\(t_addr\) )?`(0x[0-9a-fA-F]+)`")
RE_END = re.compile(r"(?<![\w.])(?<!text )end `(0x[0-9a-fA-F]+)`")


def datapoints(sec):
    """Count datapoint entries under the section's Datapoints line."""
    for i, ln in enumerate(sec):
        if ln.startswith("- Datapoints"):
            subs = []
            for s in sec[i + 1:]:
                if not s.startswith("  "):
                    break
                subs.append(s)
            if subs:
                return sum(("EQUAL" in s or "vsync" in s) for s in subs)
            rest = ln.split(":", 1)[1] if ":" in ln else ""
            return sum(bool(re.search(r"\d", seg)) for seg in rest.split("·"))
    return 0


def check_controls(rows):
    problems = []
    ctl = [r for r in rows if r["class"] == "exe" or r["status"] == "proven"]
    if not any(r["class"] == "exe" for r in ctl):
        problems.append("control: no exe row")
    for r in ctl:
        p = r["path"]
        if "#" not in r["basis"]:
            problems.append(f"control {p}: basis {r['basis']!r} has no anchor")
            continue
        doc, anchor = r["basis"].split("#", 1)
        try:
            sec = doc_section(doc, anchor)
        except (CheckError, OSError) as e:
            problems.append(f"control {p}: {e}")
            continue
        text = "\n".join(sec)
        mb, me = RE_BASE.search(text), RE_END.search(text)
        if not mb or not me:
            problems.append(f"control {p}: section #{anchor} lacks base/end")
            continue
        if r["base"] == "-" or int(mb.group(1), 16) != int(r["base"], 16):
            problems.append(f"control {p}: doc base {mb.group(1)} != row base {r['base']}")
        if r["end"] == "-" or int(me.group(1), 16) != int(r["end"], 16):
            problems.append(f"control {p}: doc end {me.group(1)} != row end {r['end']}")
        dp = datapoints(sec)
        if dp < 3 and not any(s.startswith("- Diff") for s in sec):
            problems.append(f"control {p}: {dp} datapoints (< 3) and no diff")
    return problems


def check_rows(rows):
    problems = []
    if len(rows) != 106:
        problems.append(f"rows={len(rows)}, expected 106")
    uncl = [r["path"] for r in rows if r["class"] not in CLASSES]
    if uncl:
        problems.append(f"unclassified: {len(uncl)} ({', '.join(uncl[:5])})")
    n = count_n(rows)
    if n != 83:
        problems.append(f"N={n}, expected 83")
    return problems


def negative_control(ledger_path):
    """Shift one proven row's base by +0x100 in a scratch copy; the control check must fail."""
    scratch = ROOT / ".run/t6"
    scratch.mkdir(parents=True, exist_ok=True)
    neg = scratch / "ledger.neg.tsv"
    shutil.copyfile(ledger_path, neg)
    lines = neg.read_text().split("\n")
    victim = None
    for i, ln in enumerate(lines):
        f = ln.split("\t")
        if not ln.startswith("#") and len(f) == 6 and f[4] == "proven" and f[1] != "exe" and f[3] != "-":
            f[3] = f"0x{int(f[3], 16) + 0x100:08x}"
            lines[i], victim = "\t".join(f), f[0]
            break
    if victim is None:
        return "negative-control: no proven non-exe row to perturb"
    neg.write_text("\n".join(lines))
    rows, _ = build(neg)
    if not any(p.startswith(f"control {victim}:") for p in check_controls(rows)):
        return f"negative-control: perturbed {victim} base passed the control check"
    return None


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--ledger", default=str(ROOT / "config/loadmap.evidence.tsv"))
    ap.add_argument("--out", default=str(ROOT / "config/loadmap.tsv"))
    a = ap.parse_args()
    try:
        rows, problems = build(a.ledger)
    except CheckError as e:
        print(f"FAIL: {e}")
        return 1
    text = render(rows)
    if not a.check:
        if problems:
            print("FAIL: " + "; ".join(problems))
            return 1
        Path(a.out).write_text(text)
        print(f"rows={len(rows)} N={count_n(rows)}")
        return 0
    problems += check_rows(rows)
    problems += check_controls(rows)
    neg = negative_control(a.ledger)
    if neg:
        problems.append(neg)
    out = Path(a.out)
    if not out.exists() or out.read_text() != text:
        problems.append(f"stale: {out} differs from regenerated output (run tools/loadmap.py)")
    if problems:
        for p in problems:
            print(f"FAIL: {p}")
        return 1
    uncl = sum(r["class"] not in CLASSES for r in rows)
    print(f"rows={len(rows)} N={count_n(rows)} unclassified: {uncl} controls: OK negative-control: OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
