#!/usr/bin/env python3
"""oracle_diff.py -- compare the Ghidra function-list oracle with the function census (Phase 1.5 T2); stdlib only,
run in the container:
    dc.sh run python3 tools/oracle_diff.py [--plant-start ALIAS:ADDR] [--propose-exceptions]

Inputs: .run/census/functions.tsv (`alias start end size kind family`, end exclusive; regenerated by running
tools/census.py first when missing or older than census.py), config/ghidra/<prog>.functions.tsv (`start size source`,
tools/ghidra/dump_functions.sh; prog = SLUS_012.79 for slus_012_79, else the alias), config/oracle_exceptions.tsv
(`alias start kind basis instrument`; a row missing basis or instrument, or of another kind, is ignored, counted
`exceptions invalid`). Exception kinds (T2.c5), each a mechanical predicate re-checked every run; a row whose
predicate is false leaves the disagreement counted (`failed`):
  data-span     a ghidra-only start inside a census data-in-text span;
  unreferenced  a census-only start with 0 jal words (own file), 0 `j`/branch words in the census text region from
                outside the census function at the start, 0 aligned pointer words equal to it (own file), not an s4
                cross-program target (.run/ghidra_functions/xprog_targets.tsv, other fleet programs' jal/pointer
                words), 0 Ghidra references to it (.run/ghidra_functions/<prog>.refs.tsv, DumpFunctions.java), and the
                previous census function ends at the start with an unconditional transfer (jr, j, b) + delay slot.
--propose-exceptions writes .run/oracle/proposed_exceptions.tsv (`alias start kind predicate basis instrument`) for
every residual census-only / ghidra-only row; only predicate-true rows may be copied into the config.
C0020 line: the txn rows of config/ghidra/SLUS_012.79.switch_tables.tsv (switch functions Ghidra auto-analysis
missed) whose jr lies inside an exe cache function (`k of 10 … (source txn n)`).
Disagreement = a start in one list and not the other (class census-only | ghidra-only), or the same start with a
different end (class end-ghidra-shorter | end-ghidra-longer), after these normalisations only (counts printed):
  n1  only starts inside the binary's census text region [text start, text-end) are judged; starts outside it
      (either list) are counted `not judged: n`, never dropped silently (G35).
  n2  two ends are equal when every 32-bit word between them is zero (alignment nops); bytes are read from
      .run/extracted/retail/files/<loadmap path>, nothing about them is written.
Staleness: each cache header carries `generator sha256=` = sha256(DumpFunctions.java bytes + dump_functions.sh bytes +
xprog_targets.py bytes + "<ghidra>\n<loadmap sha1>\n<loadmap base>\n"); recomputed here from the current files and config/loadmap.tsv, a
mismatch prints `stale: <prog>`. Controls every run (G25): a planted census start must be detected, a perturbed
hash input must read stale. Full disagreement list: .run/oracle/disagreements.tsv (a --plant-start run writes
.run/oracle/plant.tsv instead), each row with evidence columns: src (ghidra source auto|txn, - if none), jal_ref
(jal words in the binary's own bytes targeting the start), prev_ends_jr (word at start-8 is `jr ra`), in_data_span
(census data-in-text span kind containing the start, else -), parent (c:<start> census function / g:<start> Ghidra
function strictly containing the start, from the list lacking it; - for end-* rows), and from the Ghidra evidence
sidecar .run/ghidra_functions/<prog>.evidence.tsv (T2.c3; written by DumpFunctions.java, copied into the volume by
dump_functions.sh): g_name, g_symsrc (DEFAULT|IMPORTED|ANALYSIS|USER_DEFINED), g_call (call refs to the start),
g_jump (jump refs from outside the function), g_seed (auto|s1..s4, T2.c4) of the Ghidra function at the start, - when
Ghidra has none there; n/a when the sidecar is absent or its starts differ from the cache's (`evidence: n of 83
sidecars joined`); xj (T2.c4) = `j` (opcode 000010) words in the binary's census text region targeting the start from
outside the census function containing it. A per-class x evidence breakdown is printed.
Exit: 0 iff 83 of 83 compared, 0 disagreements, no stale cache, controls ok; 1 otherwise; 2 REFUSED (empty census or
0 caches).
"""
import argparse
import bisect
import contextlib
import hashlib
import io
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
import census  # noqa: E402  (load_fleet, parse_yaml; never modified here)

CENSUS_PY = ROOT / "tools/census.py"
CENSUS_TSV = ROOT / ".run/census/functions.tsv"
GHIDRA_DIR = ROOT / "config/ghidra"
EXCEPTIONS = ROOT / "config/oracle_exceptions.tsv"
GEN_FILES = (ROOT / "tools/ghidra/scripts/DumpFunctions.java", ROOT / "tools/ghidra/dump_functions.sh",
             ROOT / "tools/ghidra/xprog_targets.py")
FILES = ROOT / ".run/extracted/retail/files"
EVIDENCE = ROOT / ".run/ghidra_functions"
SWITCHES = ROOT / "config/ghidra/SLUS_012.79.switch_tables.tsv"
KIND_OF = {"ghidra-only": "data-span", "census-only": "unreferenced"}
OUT = ROOT / ".run/oracle"
CLASSES = ("census-only", "ghidra-only", "end-ghidra-shorter", "end-ghidra-longer")
JR_RA = 0x03E00008


def prog_of(alias):
    return "SLUS_012.79" if alias == "slus_012_79" else alias


def gen_hash(ver, sha1, base):
    h = hashlib.sha256()
    for f in GEN_FILES:
        h.update(f.read_bytes())
    h.update(("%s\n%s\n%s\n" % (ver, sha1, base)).encode())
    return h.hexdigest()


def read_cache(path):
    """-> (header dict, {start: end}, noncontig, no_text, {start: source})"""
    hdr, funcs, nc, notext, src = {}, {}, 0, False, {}
    for line in path.read_text().splitlines():
        if line.startswith("# generator "):
            hdr = dict(kv.split("=", 1) for kv in line[len("# generator "):].split())
        elif line.startswith("# non-contiguous bodies:"):
            nc = int(line.split(":")[1])
        elif line == "# no-text":
            notext = True
        elif line and not line.startswith("#"):
            s, z, so = (line.split("\t") + ["-"])[:3]
            funcs[int(s, 16)] = int(s, 16) + int(z, 16)
            src[int(s, 16)] = so
    return hdr, funcs, nc, notext, src


def read_evidence(prog, starts):
    """-> {start: (name, symsrc, call, jump, seed)} from the sidecar, or None when absent / not matching the cache starts."""
    path = EVIDENCE / (prog + ".evidence.tsv")
    if not path.exists():
        return None
    ev = {}
    for line in path.read_text().splitlines():
        if line and not line.startswith("#"):
            r = line.split("\t")
            ev[int(r[0], 16)] = (r[3], r[4], r[5], r[6], r[8] if len(r) > 8 else "-")
    return ev if set(ev) == set(starts) else None


def read_refs(prog):
    """-> {to: Ghidra reference count} from .run/ghidra_functions/<prog>.refs.tsv, or None when absent."""
    path = EVIDENCE / (prog + ".refs.tsv")
    if not path.exists():
        return None
    return {int(r[0], 16): int(r[1]) for r in (l.split("\t") for l in path.read_text().splitlines())
            if r[0] and not r[0].startswith("#")}


def branch_target(w, v):
    """target of a conditional/unconditional branch word at v (beq..bgtzl, regimm, bc1/bc2), else None."""
    op, rs, rt = w >> 26, (w >> 21) & 31, (w >> 16) & 31
    if op in (4, 5, 6, 7, 20, 21, 22, 23) or (op == 1 and rt in (0, 1, 2, 3, 16, 17, 18, 19)) \
            or (op in (16, 17, 18) and rs == 8):
        off = w & 0xFFFF
        return v + 4 + ((off - 0x10000 if off & 0x8000 else off) << 2)
    return None


def code_reader(b):
    """-> (fn(v) -> 32-bit word at vaddr v (None outside the file), {target: n jal words in the file},
    {target: [vaddr of each `j` word in the census text region]}, {target: [vaddr of each branch word in the census
    text region]}, {value: n aligned words in the file})."""
    _, segs = census.parse_yaml(ROOT / "config/splat" / (b.alias + ".yaml"))
    data = (FILES / b.path).read_bytes()
    seg = [s for s in segs if s["type"] == "code"][0]

    def word(v):
        off = seg["start"] + (v - seg["vram"])
        return int.from_bytes(data[off:off + 4], "little") if 0 <= off <= len(data) - 4 else None
    jal, jmp, br, ptr = {}, {}, {}, {}
    for off in range(0, len(data) - 3, 4):
        w = int.from_bytes(data[off:off + 4], "little")
        v = seg["vram"] + off - seg["start"]
        t = ((v + 4) & 0xF0000000) | ((w & 0x3FFFFFF) << 2)
        ptr[w] = ptr.get(w, 0) + 1
        if w >> 26 == 3:
            jal[t] = jal.get(t, 0) + 1
        elif w >> 26 == 2 and b.text[0] <= v < b.text[1]:
            jmp.setdefault(t, []).append(v)
        elif b.text[0] <= v < b.text[1] and (bt := branch_target(w, v)) is not None:
            br.setdefault(bt, []).append(v)
    return word, jal, jmp, br, ptr


def uncond(w):
    """name of an unconditional transfer word (jr rs, j, b = beq/bgez $zero), else None."""
    if w is None:
        return None
    if w >> 26 == 0 and w & 0x1FFFFF == 8:
        return "jr ra" if w == JR_RA else "jr r%d" % ((w >> 21) & 31)
    if w >> 26 == 2:
        return "j"
    return "b" if w >> 16 in (0x1000, 0x0401) else None


def pred_data_span(spans, s):
    """data-span: (true?, basis) -- the start lies inside a census data-in-text span."""
    sp = next(((x, e, k) for x, e, k in spans if x <= s < e), None)
    return sp is not None, sp and "in census %s span [0x%08x,0x%08x)" % (sp[2], sp[0], sp[1])


def pred_unreferenced(ca, s, word, jal, jmp, br, ptr, xprog, grefs):
    """unreferenced: (true?, basis) -- see the module doc; grefs None (no refs sidecar) is false."""
    cs = s if s in ca else parent(ca, s)
    out = sum(cs is None or not cs <= v < ca[cs] for v in jmp.get(s, []) + br.get(s, []))
    g = None if grefs is None else grefs.get(s, 0)
    refs = (jal.get(s, 0), out, ptr.get(s, 0), int(s in xprog), g)
    prev = max((x for x in ca if x < s), default=None)
    tr = uncond(word(s - 8)) if prev is not None and ca[prev] == s else None
    ok = tr is not None and g is not None and not any(refs)
    return ok, "prev 0x%08x ends %s; refs 0" % (prev, tr) if ok else "prev %s ends %s; jal %d xj/br %d ptr %d xprog %d ghidra %s" % (
        "-" if prev is None else "0x%08x" % prev, tr, *refs[:4], "n/a" if g is None else g)


def parent(fs, s):
    """the function in {start: end} fs strictly containing s (start < s < end), else None."""
    ks = sorted(fs)
    i = bisect.bisect_left(ks, s) - 1
    return ks[i] if i >= 0 and fs[ks[i]] > s else None


def data_spans(bins):
    """-> {alias: [(s, e, kind)]} census data-in-text spans (census.run, output discarded; `make split` first when an
    asm dir is missing, as census.py does -- dc.sh sync drops them)."""
    if any(b.text is not None and not Path(b.asm_dir).is_dir() for b in bins.values()):
        OUT.mkdir(parents=True, exist_ok=True)
        with open(OUT / "split.log", "w") as log:
            subprocess.run(["make", "-s", "-j", "split"], cwd=ROOT, stdout=log, stderr=subprocess.STDOUT)
    with contextlib.redirect_stdout(io.StringIO()):
        _, res = census.run(bins, False, write=False)
    return {a: r["data"] for a, r in res.items()}


def zero_between(word, a, b):
    lo, hi = min(a, b), max(a, b)
    if lo % 4 or hi % 4:
        return False
    return all(word(v) == 0 for v in range(lo, hi, 4))


def compare(b, cen, gh, word, cnt):
    """-> list of (class, start, census_end, ghidra_end); updates cnt['nj_c'], cnt['nj_g'], cnt['n2']."""
    if b.text is None:
        cnt["nj_c"] += len(cen); cnt["nj_g"] += len(gh)
        return []
    ts, te = b.text
    inside = lambda s: ts <= s < te
    c = {s: e for s, e in cen.items() if inside(s)}
    g = {s: e for s, e in gh.items() if inside(s)}
    cnt["nj_c"] += len(cen) - len(c); cnt["nj_g"] += len(gh) - len(g)
    out = []
    for s in sorted(set(c) | set(g)):
        if s not in g:
            out.append(("census-only", s, c[s], None))
        elif s not in c:
            out.append(("ghidra-only", s, None, g[s]))
        elif c[s] != g[s]:
            if zero_between(word, c[s], g[s]):
                cnt["n2"] += 1
            else:
                out.append(("end-ghidra-shorter" if g[s] < c[s] else "end-ghidra-longer", s, c[s], g[s]))
    return out


def ensure_census():
    if not CENSUS_TSV.exists() or CENSUS_TSV.stat().st_mtime < CENSUS_PY.stat().st_mtime:
        print("oracle: running tools/census.py (functions.tsv missing or older than census.py)")
        subprocess.run([sys.executable, str(CENSUS_PY)], stdout=subprocess.DEVNULL)
    cen = {}
    if CENSUS_TSV.exists():
        for r in census.rows(CENSUS_TSV):
            cen.setdefault(r[0], {})[int(r[1], 16)] = int(r[2], 16)
    return cen


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--plant-start", metavar="ALIAS:ADDR", help="inject a census start (control; must exit 1)")
    ap.add_argument("--propose-exceptions", action="store_true",
                    help="write .run/oracle/proposed_exceptions.tsv (residual rows with their kind predicate)")
    args = ap.parse_args(argv)
    cen = ensure_census()
    if not cen:
        print("REFUSED: empty census (%s)" % CENSUS_TSV.relative_to(ROOT))
        return 2
    if args.plant_start:
        pa, pv = args.plant_start.split(":")
        pv = int(pv, 16)
        cen.setdefault(pa, {})[pv] = pv + 4
        print("plant: census start %s:0x%08x injected" % (pa, pv))
    bins = census.load_fleet()
    dspans = data_spans(bins)
    lm = {r[0]: r for r in census.rows(census.LOADMAP) if len(r) > 3 and r[3] in ("exe", "code")}
    exc, invalid = set(), 0
    if EXCEPTIONS.exists():
        for r in census.rows(EXCEPTIONS):
            r += [""] * (5 - len(r))
            if not r[3].strip() or not r[4].strip() or r[2] not in KIND_OF.values():
                invalid += 1
            else:
                exc.add((r[0], int(r[1], 16), r[2]))
    cnt = {"nj_c": 0, "nj_g": 0, "n2": 0}
    xprog = set()
    if (EVIDENCE / "xprog_targets.tsv").exists():
        for r in census.rows(EVIDENCE / "xprog_targets.tsv"):
            xprog.add((r[0], int(r[1], 16)))
    ek = {kd: {"applied": 0, "failed": 0} for kd in KIND_OF.values()}
    props, c0020 = [], None
    k, stale, nc, dis, ctl_case, applied, joined = 0, [], 0, [], None, 0, 0
    for alias in sorted(bins):
        b = bins[alias]
        cache = GHIDRA_DIR / (prog_of(alias) + ".functions.tsv")
        if not cache.exists():
            print("missing cache: %s" % cache.relative_to(ROOT))
            continue
        hdr, gh, n, notext, gsrc = read_cache(cache)
        sha1, base = lm[b.path][2], lm[b.path][5]
        if hdr.get("sha256") != gen_hash(hdr.get("ghidra", ""), sha1, base):
            stale.append(prog_of(alias))
            print("stale: %s" % prog_of(alias))
            continue
        k += 1
        nc += n
        gev = read_evidence(prog_of(alias), gh)
        joined += gev is not None
        word, jal, jmp, br, ptr = code_reader(b) if b.text is not None else (None, {}, {}, {}, {})
        ca = cen.get(alias, {})
        grefs = read_refs(prog_of(alias))
        xp = {t for p, t in xprog if p == prog_of(alias)}
        if alias == "slus_012_79" and SWITCHES.exists():
            tx = [int(r[0], 16) for r in census.rows(SWITCHES) if len(r) > 4 and r[4] == "txn"]
            fs = [s for s in (j if j in gh else parent(gh, j) for j in tx) if s is not None]
            c0020 = (len(fs), len(tx), sum(gsrc.get(s) == "txn" for s in fs))
        for d in compare(b, ca, gh, word, cnt):
            s = d[1]
            kind = KIND_OF.get(d[0])
            if kind:
                pq = pred_data_span(dspans.get(alias, []), s) if kind == "data-span" else pred_unreferenced(
                    ca, s, word, jal, jmp, br, ptr, xp, grefs)
                if (alias, s, kind) in exc:
                    if pq[0]:
                        applied += 1
                        ek[kind]["applied"] += 1
                        continue
                    ek[kind]["failed"] += 1
                props.append((alias, s, kind, pq[0], pq[1] or "-"))
            par = None
            if d[0] == "census-only":
                par = parent(gh, s); par = par and "g:0x%08x" % par
            elif d[0] == "ghidra-only":
                par = parent(ca, s); par = par and "c:0x%08x" % par
            cs = s if s in ca else parent(ca, s)
            xj = sum(cs is None or not cs <= v < ca[cs] for v in jmp.get(s, ()))
            ev = (gsrc.get(s, "-"), jal.get(s, 0), "yes" if word(s - 8) == JR_RA else "no",
                  next((k for x, e, k in dspans.get(alias, []) if x <= s < e), "-"), par or "-") + (
                  ("n/a",) * 5 if gev is None else gev.get(s, ("-",) * 5)) + (xj,)
            dis.append((alias,) + d + ev)
        if ctl_case is None and b.text is not None and gh:
            ctl_case = (b, alias, gh, word, sha1, base, hdr.get("ghidra", ""))
    if k == 0:
        print("REFUSED: 0 caches compared")
        return 2
    # controls (G25)
    ok_plant = ok_stale = False
    if ctl_case:
        b, alias, gh, word, sha1, base, ver = ctl_case
        c = dict(cen.get(alias, {}))
        v = next(x for x in range(b.text[0], b.text[1], 4) if x not in c and x not in gh)
        c[v] = v + 4
        dc = {"nj_c": 0, "nj_g": 0, "n2": 0}
        ok_plant = any(d[0] == "census-only" and d[1] == v for d in compare(b, c, gh, word, dc))
        ok_stale = gen_hash(ver, sha1, base) != gen_hash(ver, sha1, base + "x")
    print("control: planted start detected %s" % ("ok" if ok_plant else "FAIL"))
    print("control: stale hash detected %s" % ("ok" if ok_stale else "FAIL"))
    print("normalisation n1: not judged: %d (census %d, ghidra %d; start outside census text region)" % (
        cnt["nj_c"] + cnt["nj_g"], cnt["nj_c"], cnt["nj_g"]))
    print("normalisation n2: zero-word ends equal: %d" % cnt["n2"])
    print("ghidra non-contiguous bodies: %d" % nc)
    print("exceptions valid: %d, applied: %d" % (len(exc), applied))
    print("exceptions invalid: %d" % invalid)
    for kd, v in ek.items():
        print("exceptions %s: valid %d, applied %d, failed %d (predicate false: counted as disagreements)" % (
            kd, sum(e[2] == kd for e in exc), v["applied"], v["failed"]))
    if c0020:
        print("C0020: %d of %d exe switch functions present (source txn %d)" % c0020)
    print("evidence: %d of %d sidecars joined" % (joined, k))
    for cl in CLASSES:
        rows = [d for d in dis if d[1] == cl]
        ex = " ".join("%s:0x%08x" % (d[0], d[2]) for d in rows[:5])
        print("class %s: %d%s" % (cl, len(rows), ("  e.g. " + ex) if ex else ""))
    print("breakdown: class n | src auto/txn/- | jal_ref>0 | prev_ends_jr | in_data_span | parent"
          " | g_symsrc D/I/A/U/-/na | g_call>0 | g_jump>0 | g_seed auto/s1/s2/s3/s4/-/na | xj>0")
    for cl in CLASSES:
        rows = [d for d in dis if d[1] == cl]
        if rows:
            pos = lambda x: x not in ("-", "n/a") and int(x) > 0
            print("  %s %d | %d/%d/%d | %d | %d | %d | %d | %s | %d | %d | %s | %d" % (
                cl, len(rows), sum(d[5] == "auto" for d in rows), sum(d[5] == "txn" for d in rows),
                sum(d[5] == "-" for d in rows), sum(d[6] > 0 for d in rows), sum(d[7] == "yes" for d in rows),
                sum(d[8] != "-" for d in rows), sum(d[9] != "-" for d in rows),
                "/".join(str(sum(d[11] == v for d in rows))
                         for v in ("DEFAULT", "IMPORTED", "ANALYSIS", "USER_DEFINED", "-", "n/a")),
                sum(pos(d[12]) for d in rows), sum(pos(d[13]) for d in rows),
                "/".join(str(sum(d[14] == v for d in rows)) for v in ("auto", "s1", "s2", "s3", "s4", "-", "n/a")),
                sum(d[15] > 0 for d in rows)))
    OUT.mkdir(parents=True, exist_ok=True)
    fmt = lambda x: "-" if x is None else "0x%08x" % x
    (OUT / ("plant.tsv" if args.plant_start else "disagreements.tsv")).write_text(
        "# alias\tclass\tstart\tcensus_end\tghidra_end\tsrc\tjal_ref\tprev_ends_jr\tin_data_span\tparent"
        "\tg_name\tg_symsrc\tg_call\tg_jump\tg_seed\txj\n" +
        "".join("%s\t%s\t0x%08x\t%s\t%s\t%s\t%d\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%d\n" % (a, cl, s, fmt(ce), fmt(ge), *ev)
                for a, cl, s, ce, ge, *ev in dis))
    if args.propose_exceptions:
        inst = {"data-span": "tools/census.py data spans",
                "unreferenced": "tools/oracle_diff.py:%d" % pred_unreferenced.__code__.co_firstlineno}
        (OUT / "proposed_exceptions.tsv").write_text("# alias\tstart\tkind\tpredicate\tbasis\tinstrument\n" + "".join(
            "%s\t0x%08x\t%s\t%s\t%s\t%s\n" % (a, s, kd, "true" if ok else "false", bs, inst[kd])
            for a, s, kd, ok, bs in props))
        print("proposed exceptions: %d (predicate true %d) -> .run/oracle/proposed_exceptions.tsv" % (
            len(props), sum(p[3] for p in props)))
    if args.plant_start:
        hit = any(d[0] == pa and d[2] == pv for d in dis)
        print("plant: %s:0x%08x %s" % (pa, pv, "reported as a disagreement" if hit else
                                       "NOT a disagreement (outside census text region -> n1 not judged, or a Ghidra start)"))
    n = len(bins)
    print("oracle: %d of %d binaries compared, %d disagreements" % (k, n, len(dis)))
    good = k == n == census.FLEET_N and not dis and not stale and ok_plant and ok_stale
    return 0 if good else 1


if __name__ == "__main__":
    sys.exit(main())
