#!/usr/bin/env python3
"""oracle_diff.py -- compare the Ghidra function-list oracle with the function census (Phase 1.5 T2); stdlib only,
run in the container:
    dc.sh run python3 tools/oracle_diff.py [--plant-start ALIAS:ADDR]

Inputs: .run/census/functions.tsv (`alias start end size kind family`, end exclusive; regenerated by running
tools/census.py first when missing or older than census.py), config/ghidra/<prog>.functions.tsv (`start size source`,
tools/ghidra/dump_functions.sh; prog = SLUS_012.79 for slus_012_79, else the alias), config/oracle_exceptions.tsv
(`alias start kind basis instrument`; a row missing basis or instrument is ignored, counted `exceptions invalid`).
Disagreement = a start in one list and not the other (class census-only | ghidra-only), or the same start with a
different end (class end-ghidra-shorter | end-ghidra-longer), after these normalisations only (counts printed):
  n1  only starts inside the binary's census text region [text start, text-end) are judged; starts outside it
      (either list) are counted `not judged: n`, never dropped silently (G35).
  n2  two ends are equal when every 32-bit word between them is zero (alignment nops); bytes are read from
      .run/extracted/retail/files/<loadmap path>, nothing about them is written.
Staleness: each cache header carries `generator sha256=` = sha256(DumpFunctions.java bytes + dump_functions.sh bytes +
"<ghidra>\n<loadmap sha1>\n<loadmap base>\n"); recomputed here from the current files and config/loadmap.tsv, a
mismatch prints `stale: <prog>`. Controls every run (G25): a planted census start must be detected, a perturbed
hash input must read stale. Full disagreement list: .run/oracle/disagreements.tsv.
Exit: 0 iff 83 of 83 compared, 0 disagreements, no stale cache, controls ok; 1 otherwise; 2 REFUSED (empty census or
0 caches).
"""
import argparse
import hashlib
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
import census  # noqa: E402  (load_fleet, parse_yaml; never modified here)

CENSUS_PY = ROOT / "tools/census.py"
CENSUS_TSV = ROOT / ".run/census/functions.tsv"
GHIDRA_DIR = ROOT / "config/ghidra"
EXCEPTIONS = ROOT / "config/oracle_exceptions.tsv"
GEN_FILES = (ROOT / "tools/ghidra/scripts/DumpFunctions.java", ROOT / "tools/ghidra/dump_functions.sh")
FILES = ROOT / ".run/extracted/retail/files"
OUT = ROOT / ".run/oracle"
CLASSES = ("census-only", "ghidra-only", "end-ghidra-shorter", "end-ghidra-longer")


def prog_of(alias):
    return "SLUS_012.79" if alias == "slus_012_79" else alias


def gen_hash(ver, sha1, base):
    h = hashlib.sha256()
    for f in GEN_FILES:
        h.update(f.read_bytes())
    h.update(("%s\n%s\n%s\n" % (ver, sha1, base)).encode())
    return h.hexdigest()


def read_cache(path):
    """-> (header dict, {start: end}, noncontig, no_text)"""
    hdr, funcs, nc, notext = {}, {}, 0, False
    for line in path.read_text().splitlines():
        if line.startswith("# generator "):
            hdr = dict(kv.split("=", 1) for kv in line[len("# generator "):].split())
        elif line.startswith("# non-contiguous bodies:"):
            nc = int(line.split(":")[1])
        elif line == "# no-text":
            notext = True
        elif line and not line.startswith("#"):
            s, z = line.split("\t")[:2]
            funcs[int(s, 16)] = int(s, 16) + int(z, 16)
    return hdr, funcs, nc, notext


def code_reader(b):
    """-> fn(v) -> 32-bit word at vaddr v (None if outside the file's code segment)."""
    _, segs = census.parse_yaml(ROOT / "config/splat" / (b.alias + ".yaml"))
    data = (FILES / b.path).read_bytes()
    seg = [s for s in segs if s["type"] == "code"][0]

    def word(v):
        off = seg["start"] + (v - seg["vram"])
        return int.from_bytes(data[off:off + 4], "little") if 0 <= off <= len(data) - 4 else None
    return word


def zero_between(word, a, b):
    lo, hi = min(a, b), max(a, b)
    if lo % 4 or hi % 4:
        return False
    return all(word(v) == 0 for v in range(lo, hi, 4))


def compare(b, cen, gh, word, cnt):
    """-> list of (class, start, census_end, ghidra_end); updates cnt['nj_c'], cnt['nj_g'], cnt['n2']."""
    if b.text is None:
        cnt["nj_c"] += len(cen); cnt["nj_g"] += len(gh)
        return []
    ts, te = b.text
    inside = lambda s: ts <= s < te
    c = {s: e for s, e in cen.items() if inside(s)}
    g = {s: e for s, e in gh.items() if inside(s)}
    cnt["nj_c"] += len(cen) - len(c); cnt["nj_g"] += len(gh) - len(g)
    out = []
    for s in sorted(set(c) | set(g)):
        if s not in g:
            out.append(("census-only", s, c[s], None))
        elif s not in c:
            out.append(("ghidra-only", s, None, g[s]))
        elif c[s] != g[s]:
            if zero_between(word, c[s], g[s]):
                cnt["n2"] += 1
            else:
                out.append(("end-ghidra-shorter" if g[s] < c[s] else "end-ghidra-longer", s, c[s], g[s]))
    return out


def ensure_census():
    if not CENSUS_TSV.exists() or CENSUS_TSV.stat().st_mtime < CENSUS_PY.stat().st_mtime:
        print("oracle: running tools/census.py (functions.tsv missing or older than census.py)")
        subprocess.run([sys.executable, str(CENSUS_PY)], stdout=subprocess.DEVNULL)
    cen = {}
    if CENSUS_TSV.exists():
        for r in census.rows(CENSUS_TSV):
            cen.setdefault(r[0], {})[int(r[1], 16)] = int(r[2], 16)
    return cen


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--plant-start", metavar="ALIAS:ADDR", help="inject a census start (control; must exit 1)")
    args = ap.parse_args(argv)
    cen = ensure_census()
    if not cen:
        print("REFUSED: empty census (%s)" % CENSUS_TSV.relative_to(ROOT))
        return 2
    if args.plant_start:
        pa, pv = args.plant_start.split(":")
        pv = int(pv, 16)
        cen.setdefault(pa, {})[pv] = pv + 4
        print("plant: census start %s:0x%08x injected" % (pa, pv))
    bins = census.load_fleet()
    lm = {r[0]: r for r in census.rows(census.LOADMAP) if len(r) > 3 and r[3] in ("exe", "code")}
    exc, invalid = set(), 0
    if EXCEPTIONS.exists():
        for r in census.rows(EXCEPTIONS):
            r += [""] * (5 - len(r))
            if not r[3].strip() or not r[4].strip():
                invalid += 1
            else:
                exc.add((r[0], int(r[1], 16), r[2]))
    cnt = {"nj_c": 0, "nj_g": 0, "n2": 0}
    k, stale, nc, dis, ctl_case, applied = 0, [], 0, [], None, 0
    for alias in sorted(bins):
        b = bins[alias]
        cache = GHIDRA_DIR / (prog_of(alias) + ".functions.tsv")
        if not cache.exists():
            print("missing cache: %s" % cache.relative_to(ROOT))
            continue
        hdr, gh, n, notext = read_cache(cache)
        sha1, base = lm[b.path][2], lm[b.path][5]
        if hdr.get("sha256") != gen_hash(hdr.get("ghidra", ""), sha1, base):
            stale.append(prog_of(alias))
            print("stale: %s" % prog_of(alias))
            continue
        k += 1
        nc += n
        word = code_reader(b) if b.text is not None else None
        for d in compare(b, cen.get(alias, {}), gh, word, cnt):
            if (alias, d[1], d[0]) in exc:
                applied += 1
            else:
                dis.append((alias,) + d)
        if ctl_case is None and b.text is not None and gh:
            ctl_case = (b, alias, gh, word, sha1, base, hdr.get("ghidra", ""))
    if k == 0:
        print("REFUSED: 0 caches compared")
        return 2
    # controls (G25)
    ok_plant = ok_stale = False
    if ctl_case:
        b, alias, gh, word, sha1, base, ver = ctl_case
        c = dict(cen.get(alias, {}))
        v = next(x for x in range(b.text[0], b.text[1], 4) if x not in c and x not in gh)
        c[v] = v + 4
        dc = {"nj_c": 0, "nj_g": 0, "n2": 0}
        ok_plant = any(d[0] == "census-only" and d[1] == v for d in compare(b, c, gh, word, dc))
        ok_stale = gen_hash(ver, sha1, base) != gen_hash(ver, sha1, base + "x")
    print("control: planted start detected %s" % ("ok" if ok_plant else "FAIL"))
    print("control: stale hash detected %s" % ("ok" if ok_stale else "FAIL"))
    print("normalisation n1: not judged: %d (census %d, ghidra %d; start outside census text region)" % (
        cnt["nj_c"] + cnt["nj_g"], cnt["nj_c"], cnt["nj_g"]))
    print("normalisation n2: zero-word ends equal: %d" % cnt["n2"])
    print("ghidra non-contiguous bodies: %d" % nc)
    print("exceptions valid: %d, applied: %d" % (len(exc), applied))
    print("exceptions invalid: %d" % invalid)
    for cl in CLASSES:
        rows = [d for d in dis if d[1] == cl]
        ex = " ".join("%s:0x%08x" % (d[0], d[2]) for d in rows[:5])
        print("class %s: %d%s" % (cl, len(rows), ("  e.g. " + ex) if ex else ""))
    OUT.mkdir(parents=True, exist_ok=True)
    fmt = lambda x: "-" if x is None else "0x%08x" % x
    (OUT / "disagreements.tsv").write_text("# alias\tclass\tstart\tcensus_end\tghidra_end\n" + "".join(
        "%s\t%s\t0x%08x\t%s\t%s\n" % (a, cl, s, fmt(ce), fmt(ge)) for a, cl, s, ce, ge in dis))
    if args.plant_start:
        hit = any(d[0] == pa and d[2] == pv for d in dis)
        print("plant: %s:0x%08x %s" % (pa, pv, "reported as a disagreement" if hit else
                                       "NOT a disagreement (outside census text region -> n1 not judged, or a Ghidra start)"))
    n = len(bins)
    print("oracle: %d of %d binaries compared, %d disagreements" % (k, n, len(dis)))
    good = k == n == census.FLEET_N and not dis and not stale and ok_plant and ok_stale
    return 0 if good else 1


if __name__ == "__main__":
    sys.exit(main())
