#!/usr/bin/env python3
"""tools/splat_gen.py -- generate / check the per-binary splat configs (T2, Phase 1.3).

Inputs: config/loadmap.tsv (fleet = class exe|code) + config/boundaries.tsv + config/c_units.tsv. Outputs, per
fleet row: config/splat/<alias>.yaml and config/check.<alias>.sha (`<loadmap sha1>  <alias>.bin`).
Only sha1 hex, addresses and boundaries.tsv basis text are written (G12); the exe is read only
for its header pc0 and the startup $gp immediates.

  splat_gen.py [--force] [--only <alias>] [--out-dir <dir>]   write (refuses to overwrite w/o --force)
  splat_gen.py --check [--only <alias>] [--out-dir <dir>]     assert the written files, exit 0 iff OK

Cuts: edges = {0, size} + every boundaries start/end as file offset (+ 0x800 for the exe header).
C units (c_units.tsv): each start is a further cut; [start, next cut) -> `c` named <unit> (T6).
Types: jtbl -> rodata; [text_start, text_end) -> asm; [base, text_start) -> rodata; after -> data.
text_start: exe = pc0; overlay = max jtbl end (base if none), moved to the first `addiu $sp,$sp,-N` when the
words before it hold a MIPS II+ encoding (data head, head_end).
"""
import argparse
import re
import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LOADMAP = ROOT / "config/loadmap.tsv"
BOUNDARIES = ROOT / "config/boundaries.tsv"
C_UNITS = ROOT / "config/c_units.tsv"
FILES = ROOT / "extracted/retail/files"
EXE_PATH = "SLUS_012.79"
EXE_BASE = 0x80018000
EXE_HDR = 0x800
EXE_PC0 = 0x8001B3B8
GP_SCAN = 64  # instructions scanned from pc0
PATH_ROOTS = ("asm/", "build/", "assets/", "src/")
HEAD = "# config/splat/{a}.yaml -- generated by tools/splat_gen.py from config/loadmap.tsv + config/boundaries.tsv; do not hand-edit.\n"


def alias_of(path):
    p = path.lower()
    if p.endswith(".bin"):
        p = p[:-4]
    return p.replace("/", "_").replace(".", "_")


def read_tsv(path, cols):
    rows = []
    for line in path.read_text().splitlines():
        if not line or line.startswith("#"):
            continue
        f = line.split("\t")
        rows.append(dict(zip(cols, f)))
    return rows


def fleet():
    rows = read_tsv(LOADMAP, ("path", "size", "sha1", "class", "route", "base", "end", "status"))
    n = None
    for line in LOADMAP.read_text().splitlines():
        m = re.match(r"# N = (\d+)", line)
        if m:
            n = int(m.group(1))
    out = [r for r in rows if r["class"] in ("exe", "code")]
    for r in out:
        r["size"] = int(r["size"])
        r["base"] = None if r["base"] == "-" else int(r["base"], 16)
        r["alias"] = alias_of(r["path"])
    return out, n


def boundaries():
    by = {}
    for r in read_tsv(BOUNDARIES, ("binary", "kind", "start", "end", "basis")):
        r["start"], r["end"] = int(r["start"], 16), int(r["end"], 16)
        by.setdefault(r["binary"], []).append(r)
    for v in by.values():
        v.sort(key=lambda r: (r["start"], r["kind"], r["end"], r["basis"]))
    return by


def c_units():
    by = {}
    for r in read_tsv(C_UNITS, ("alias", "start", "unit", "notes")):
        r["start"] = int(r["start"], 16)
        by.setdefault(r["alias"], []).append(r)
    return by


def off_of(row, addr):
    if row["class"] == "exe":
        return addr - EXE_BASE + EXE_HDR
    return addr - row["base"]


def exe_gp():
    """Return (gp, [(file_off, insn text)]) from the startup at pc0, or (None, reason)."""
    f = FILES / EXE_PATH
    if not f.exists():
        return None, f"absent: {f.relative_to(ROOT)}"
    data = f.read_bytes()
    pc0 = struct.unpack_from("<I", data, 0x10)[0]
    if pc0 != EXE_PC0:
        return None, f"header pc0 0x{pc0:08x} != 0x{EXE_PC0:08x}"
    start = pc0 - EXE_BASE + EXE_HDR
    hi, ev = None, []
    for i in range(GP_SCAN):
        o = start + 4 * i
        w = struct.unpack_from("<I", data, o)[0]
        op, rs, rt, imm = w >> 26, (w >> 21) & 31, (w >> 16) & 31, w & 0xFFFF
        if rt != 28:
            continue
        if op == 0x0F:
            hi = imm << 16
            ev = [(o, f"lui $gp,0x{imm:x}")]
        elif hi is not None and rs == 28 and op in (0x09, 0x0D):
            if op == 0x09:
                lo = imm - 0x10000 if imm & 0x8000 else imm
                ev.append((o, f"addiu $gp,$gp,{lo:#x}"))
            else:
                lo = imm
                ev.append((o, f"ori $gp,$gp,0x{imm:x}"))
            return (hi + lo) & 0xFFFFFFFF, ev
    return None, f"no lui/addiu|ori $gp in {GP_SCAN} insns from pc0 (file +0x{start:x})"


def mips2plus(w):
    """True iff rabbitizer decodes w as an instruction gas -march=r3000 rejects (MIPS II/III; jalr rd==rs)."""
    op, fn = w >> 26, w & 0x3F
    if op == 0:
        return fn in (0x0A, 0x0B, 0x14, 0x16, 0x17) or 0x1C <= fn <= 0x1F or 0x2C <= fn <= 0x36 \
            or fn in (0x38, 0x3A, 0x3B, 0x3C, 0x3E, 0x3F) or (fn == 0x09 and (w >> 21) & 31 == (w >> 11) & 31)
    return 0x14 <= op <= 0x1B or op in (0x27, 0x2C, 0x2D, 0x2F) or 0x30 <= op <= 0x3F and op not in (0x32, 0x3A)


def head_end(row, text_start, text_end):
    """Overlay data head (T4): when a word in [text_start, first `addiu $sp,$sp,-N`) is mips2plus (it would not
    assemble), the whole head is data: return the prologue address; else text_start."""
    d = (FILES / row["path"]).read_bytes()
    a, bad = text_start, False
    while a < text_end:
        w = struct.unpack_from("<I", d, a - row["base"])[0]
        if w >> 16 == 0x27BD and w & 0x8000:
            return a if bad else text_start
        bad = bad or mips2plus(w)
        a += 4
    return text_start


def plan(row, rows_b, errs, units=()):
    """Return (segments, end) where segments = [(start, kind, vram|None, [(start, type, name, comment)])]."""
    a, size = row["alias"], row["size"]
    if row["base"] is None:
        return [(0, "bin", 0, [])], size
    exe = row["class"] == "exe"
    jt = [r for r in rows_b if r["kind"] == "jtbl"]
    te = [r for r in rows_b if r["kind"] == "text-end"]
    if len(te) != 1:
        errs.append(f"{row['path']}: {len(te)} text-end rows")
        return None, size
    text_end = te[0]["end"]
    text_start = EXE_PC0 if exe else max([r["end"] for r in jt], default=row["base"])
    if not exe:
        text_start = head_end(row, text_start, text_end)
    for r in jt:
        tgt = int(re.match(r"jr=(0x[0-9a-f]+)", r["basis"]).group(1), 16)
        if tgt < text_start:
            errs.append(f"{row['path']}: jtbl 0x{r['start']:08x} jr target 0x{tgt:08x} < text_start 0x{text_start:08x}")
    if text_start > text_end:
        errs.append(f"{row['path']}: text_start 0x{text_start:08x} > text_end 0x{text_end:08x}")
    edges = {0, size}
    if exe:
        edges.add(EXE_HDR)
    for r in rows_b:
        edges.add(off_of(row, r["start"]))
        edges.add(off_of(row, r["end"]))
    edges.add(off_of(row, text_start))
    cu = {}
    for u in units:
        if not text_start <= u["start"] < text_end or any(
                r["kind"] == "lib-object" and r["start"] <= u["start"] < r["end"] for r in rows_b):
            errs.append(f"{row['path']}: c unit {u['unit']} 0x{u['start']:08x} not in game text")
        cu[off_of(row, u["start"])] = u["unit"]
        edges.add(off_of(row, u["start"]))
    tail = size & ~3
    if size % 4:
        if any(tail < e < size for e in edges):
            errs.append(f"{row['path']}: edge inside the odd tail")
        edges.add(tail)
    edges = sorted(edges)
    if edges[0] != 0 or edges[-1] != size:
        errs.append(f"{row['path']}: edge outside [0, size)")
    seg0 = EXE_HDR if exe else 0
    subs = []
    for s, e in zip(edges, edges[1:]):
        if s < seg0:
            continue
        addr = (s - EXE_HDR + EXE_BASE) if exe else s + row["base"]
        notes = "; ".join(f"{r['kind']} {r['basis']}" for r in rows_b if off_of(row, r["start"]) == s)
        if size % 4 and s == tail:
            subs.append((s, "bin", f"{a}_trailing", f"final {size - tail} B (size not 4-aligned)"))
            continue
        if s in cu:
            subs.append((s, "c", cu[s], notes))
            continue
        if any(r["start"] <= addr and addr + (e - s) <= r["end"] for r in jt):
            t = "rodata"
        elif addr >= text_end:
            t = "data"
        elif addr >= text_start:
            t = "asm"
        else:
            t = "rodata"
        subs.append((s, t, f"{a}_{s:x}", notes))
    segs = []
    if exe:
        segs.append((0, "bin", None, [(0, "bin", f"{a}_0", "PS-X EXE header")]))
    segs.append((seg0, "code", row["base"], subs))
    return segs, size


def render(row, segs, end, gp):
    a = row["alias"]
    has_c = any(t == "c" for _, _, _, subs in segs for _, t, _, _ in subs)
    o = [HEAD.format(a=a), f"name: {a}\n", f"sha1: {row['sha1']}\n", "options:\n"]
    opts = [
        ("basename", a), ("platform", "psx"), ("compiler", "GCC"), ("base_path", "../.."),
        ("target_path", f"extracted/retail/files/{row['path']}"),
        ("asm_path", f"asm/{a}"), ("asset_path", f"asm/{a}/assets"), ("src_path", f"src/{a}"),
        ("build_path", f"build/{a}"), ("ld_script_path", f"build/{a}.ld"),
        ("undefined_funcs_auto_path", f"build/{a}/undefined_funcs_auto.txt"),
        ("undefined_syms_auto_path", f"build/{a}/undefined_syms_auto.txt"),
        ("generated_asm_macros_directory", f"build/{a}/include"),
        ("find_file_boundaries", "False"),
        ("section_order", '[".rodata", ".text", ".data", ".bss"]'),
        # file layout is contiguous: no 16-byte SUBALIGN/section-end padding (T3; else ld pads between sections)
        ("subalign", "4"), ("ld_align_section_vram_end", "False"),
    ]
    if has_c:
        opts.insert(6, ("nonmatchings_path", "nonmatchings"))  # splat: relative to asm_path -> asm/<a>/nonmatchings
    if gp is not None:
        opts.append(("gp_value", f"0x{gp:08x}"))
    o += [f"  {k}: {v}\n" for k, v in opts]
    o.append("segments:\n")
    if row["base"] is None:
        o.append("  # no base: loadmap base '-' (status n/a, ranked none); one raw bin at vram 0, never a guessed base\n")
        o.append(f"  - name: {a}_0\n    type: bin\n    start: 0x0\n    vram: 0x0\n")
    for start, kind, vram, subs in segs:
        if kind == "bin" and vram is None:
            s, t, n, c = subs[0]
            o.append(f"  - [0x{s:x}, {t}, {n}]  # {c}\n")
        elif kind == "code":
            o.append(f"  - name: {a}\n    type: code\n    start: 0x{start:x}\n    vram: 0x{vram:08x}\n    subsegments:\n")
            for s, t, n, c in subs:
                o.append(f"      - [0x{s:x}, {t}, {n}]" + (f"  # {c}\n" if c else "\n"))
    o.append(f"  - [0x{end:x}]\n")
    return "".join(o)


def write(args):
    rows, _ = fleet()
    if args.only:
        rows = [r for r in rows if r["alias"] == args.only]
        if not rows:
            sys.exit(f"FAIL unknown alias {args.only}")
    by, cu = boundaries(), c_units()
    gp, ev = exe_gp()
    if gp is None:
        print(f"gp: not found ({ev})")
    else:
        print(f"gp: 0x{gp:08x} " + " ".join(f"+0x{o:x} `{t}`" for o, t in ev))
    out = Path(args.out_dir)
    files, errs = {}, []
    for row in rows:
        segs, end = plan(row, by.get(row["path"], []), errs, cu.get(row["alias"], []))
        if segs is None:
            continue
        a = row["alias"]
        files[out / f"config/splat/{a}.yaml"] = render(row, segs, end, gp if row["class"] == "exe" else None)
        files[out / f"config/check.{a}.sha"] = f"{row['sha1']}  {a}.bin\n"
    if errs:
        for e in errs:
            print(f"FAIL {e}")
        sys.exit(1)
    if not args.force:
        for p in files:
            if p.exists():
                print(f"FAIL exists (use --force): {p}")
                sys.exit(1)
    for p, text in files.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_bytes(text.encode())
    print(f"wrote {len(files) // 2} yaml + {len(files) // 2} sha under {out}")


SUB = re.compile(r"^      - \[0x([0-9a-f]+), (\w+), (\w+)\]")
TOP = re.compile(r"^  - \[0x([0-9a-f]+)(?:, (\w+), (\w+))?\]")


def parse(text):
    """Return (pieces [(start, type, name, vram_of_segment)], end, seg_starts, opts)."""
    pieces, segs, opts, end, cur = [], [], {}, None, None
    for line in text.splitlines():
        m = re.match(r"^  (\w+): (.*)$", line)
        if m and not line.startswith("  - "):
            opts[m.group(1)] = m.group(2)
        m = TOP.match(line)
        if m:
            if m.group(2):
                s = int(m.group(1), 16)
                segs.append((s, None))
                pieces.append((s, m.group(2), m.group(3), None))
            else:
                end = int(m.group(1), 16)
            continue
        if line.startswith("  - name: "):
            cur = {"name": line.split(": ")[1]}
            continue
        m = re.match(r"^    (type|start|vram): (\S+)", line)
        if m and cur is not None:
            cur[m.group(1)] = m.group(2)
            if "start" in cur and "vram" in cur and "type" in cur and "_seen" not in cur:
                cur["_seen"] = 1
                segs.append((int(cur["start"], 16), int(cur["vram"], 16)))
                if cur["type"] == "bin":
                    pieces.append((int(cur["start"], 16), "bin", cur["name"], int(cur["vram"], 16)))
            continue
        m = SUB.match(line)
        if m:
            pieces.append((int(m.group(1), 16), m.group(2), m.group(3), segs[-1][1]))
    return pieces, end, segs, opts


def check(args):
    rows, n = fleet()
    by, cu = boundaries(), c_units()
    out = Path(args.out_dir)
    fails = []
    if args.only:
        rows = [r for r in rows if r["alias"] == args.only]
    else:
        ny = len(list((out / "config/splat").glob("*.yaml")))
        ns = len(list((out / "config").glob("check.*.sha")))
        if not (len(rows) == n == ny == ns):
            fails.append(f"count: loadmap N={n} fleet={len(rows)} yaml={ny} sha={ns}")
        if len({r["alias"] for r in rows}) != len(rows):
            fails.append("aliases not unique")
    bad = {k: [] for k in ("edge", "tile", "vram", "tail", "wep_s00", "sha", "paths", "missing", "c_unit")}
    known = {r["alias"] for r in fleet()[0]}
    bad["c_unit"] += [f"{a}:unknown alias" for a in cu if a not in known]
    for row in rows:
        a, size = row["alias"], row["size"]
        y, sh = out / f"config/splat/{a}.yaml", out / f"config/check.{a}.sha"
        if not y.exists() or not sh.exists():
            bad["missing"].append(a)
            continue
        if sh.read_text() != f"{row['sha1']}  {a}.bin\n":
            bad["sha"].append(a)
        pieces, end, segs, opts = parse(y.read_text())
        for k, v in opts.items():
            if k == "nonmatchings_path":
                if v != "nonmatchings":
                    bad["paths"].append(f"{a}:{k}")
            elif k.endswith("_path") and k not in ("base_path", "target_path") and not v.startswith(PATH_ROOTS):
                bad["paths"].append(f"{a}:{k}")
        starts = [p[0] for p in pieces]
        if not pieces or starts[0] != 0 or end != size or starts != sorted(set(starts)) or starts[-1] >= size:
            bad["tile"].append(a)
        for s, _ in segs:
            if s not in starts:
                bad["tile"].append(f"{a}@seg0x{s:x}")
        for s, v in segs:
            if v is not None and not any(p[0] == s for p in pieces if p[3] == v):
                bad["tile"].append(f"{a}@seg0x{s:x}")
        if row["base"] is None:
            if not (len(pieces) == 1 and pieces[0][1] == "bin" and pieces[0][3] == 0 and end == size):
                bad["wep_s00"].append(a)
            continue
        units = cu.get(a, [])
        for u in units:
            hit = [p for p in pieces if p[1] == "c" and p[0] == off_of(row, u["start"]) and p[2] == u["unit"]]
            if len(hit) != 1:
                bad["c_unit"].append(f"{a}:{u['unit']}")
        for p in pieces:
            if p[1] == "c" and not any(p[0] == off_of(row, u["start"]) and p[2] == u["unit"] for u in units):
                bad["c_unit"].append(f"{a}:{p[2]} no row")
        cuts = set(starts) | {end}
        for r in by.get(row["path"], []):
            for x in (r["start"], r["end"]):
                if off_of(row, x) not in cuts:
                    bad["edge"].append(f"{a}@0x{x:08x}")
        want = [(EXE_HDR, EXE_BASE)] if row["class"] == "exe" else [(0, row["base"])]
        if [sv for sv in segs if sv[1] is not None] != want:
            bad["vram"].append(a)
        if size % 4 and not (pieces[-1][0] == size & ~3 and pieces[-1][1] == "bin"
                             and pieces[-1][2] == f"{a}_trailing"):
            bad["tail"].append(a)
    wep = [r for r in rows if r["base"] is None]
    if not args.only and [r["path"] for r in wep] != ["BIN/WEP_S00.BIN"]:
        bad["wep_s00"].append("no-base rows: " + ",".join(r["path"] for r in wep))
    for k, v in bad.items():
        if v:
            fails.append(f"{k}: {len(v)} ({', '.join(sorted(set(v))[:5])})")
    for f in fails:
        print(f"FAIL {f}")
    if fails:
        sys.exit(1)
    print(f"OK splat_gen --check: {len(rows)} binaries under {out}")


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--force", action="store_true")
    ap.add_argument("--only")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--out-dir", default=str(ROOT))
    args = ap.parse_args()
    (check if args.check else write)(args)


if __name__ == "__main__":
    main()
